### ISSUE TITLE
Error with <field>:[x TO y]

### ISSUE THREAD

**Issue by paulcanning** [laggingreflex/luce-filter#3]
Getting the following error

> TypeError: Cannot read properties of undefined (reading 'toLowerCase')

When running the test file. Breaking on the height range test.

**Comment by paulcanning** [comment]
Easy fix,

index.js, L83

Change

`  if (!rest.quoted) {`

to

`if (term && !rest.quoted) {`

As a range filter has no `term`

**Comment by laggingreflex** [comment]
Lol, would you believe it I had already fixed it (https://github.com/laggingreflex/luce-filter/commit/ba6772faeb8fbd05e986cee2bf4aca0eb146c9ef) but forgot to push. Fixed & published.

**Comment by paulcanning** [comment]
Great minds think alike ;)
